added download selection, now download queue

diff --git a/gog_installer b/gog_installer
--- a/gog_installer
+++ b/gog_installer
@@ -23,7 +23,7 @@ if ! declare -A test_arr; then
   echo "unable to declare associative array, check bash version, needs to be 4.0 or above" >&2
   exit 1
 fi
-
+unset test_arr
 # constants
 readonly config_dir="$HOME/.config/gog_downloader"
 readonly config_file="$config_dir/config.json"
@@ -206,26 +206,38 @@ get_download_links() {
   local game_id=$1
   local game_info_url="https://api.gog.com/products/$game_id?expand=downloads,expanded_dlcs"
   local tries=0
+  # retry ping up to 3 times if it ifails
   while (( tries < 3 )); do
     (( tries++ ))
     local raw_response=$(curl -s -w "%{http_code}" -H "authorization: bearer $auth_code" "$game_info_url")
+    # gets the result code for checking
     local http_code="${raw_response: -3}"
+    # json response just so no curl a second time
     local json_body="${raw_response:0:${#raw_response}-3}"
     if [[ "$http_code" -eq "200" ]]; then
       break
     elif [[ "$http_code" -eq "401" ]]; then
       use_refresh
+      sleep 5
       continue
     fi
   done
+  # if it fails 3 times something is underlyingly wrong, exit
+  if (( $tries > 3 )); then
+    echo "failed getting download links"
+    exit 1
+  fi
+  unset downlinks patches dlcs dlcs_size
   # echo "$json_body"
-  local downlinks
+  # get the links from response, and sort them as jq returns lexographical sort
   readarray -t downlinks < <(echo "$json_body" | jq -r '.downloads.installers[].files[].downlink' | sort -V)
-  local patches
-  readarray -t patches < <(echo "$json_body" | jq -r '.downloads.patches[].files[].downlink' | sort -V)
-
-  declare -A dlcs
-  declare -A dlcs_size
+  readarray -t patches < <(echo "$json_body" | jq -r '.downloads.patches[].files[]?.downlink' | sort -V)
+  if [[ $patches == "null" ]]; then
+    patches=()
+  fi
+  # maps the dlcs to their names and sizes
+  declare -gA dlcs
+  declare -gA dlcs_size
   while IFS=$'\t' read -r name downlink size; do
     [[ -z "$name" ]] && continue
     dlcs["$name"]+="$downlink\t"
@@ -233,10 +245,12 @@ get_download_links() {
     dlcs_size["$name"]="$readable_size $unit"
   done < <(echo "$json_body" | jq -r ' .expanded_dlcs[]?.downloads.installers[]? | [.name, .files[]?.downlink, .total_size] | @tsv')
 
+  # gets the sizes and turns them from bytes into human readable format
   base_size=$(echo "$json_body" | jq -r '.downloads.installers[0].total_size')
   convert_to_human $base_size
   human_base_size="$readable_size $unit"
   patches_size=$(echo "$json_body" | jq -r '[.downloads.patches[]?.total_size] | add')
+  # some games don#t have patches so 
   if [[ "$patches_size" != "null" && -n "$patches_size" ]]; then
       convert_to_human $patches_size
       human_patches_size="$readable_size $unit"
@@ -301,9 +315,10 @@ main() {
     get_game_list
     echo "choose the game you want to download:"
     i=0
-    # a second array to map the order to the number
+    # a second array to map the order to the number, since associative isn't consistent order
     local game_internal_id_arr
     readarray -t game_internal_id_arr < <(printf '%s\n' "${!game_title_arr[@]}" | sort -f)
+    # print all the games
     for game in "${game_internal_id_arr[@]}"; do
       echo "($i): $game"
       (( i++ ))
@@ -311,10 +326,12 @@ main() {
     echo "enter the number of the game, r to refresh the game list, and q to quit:"
     local game_choice
     read -r game_choice
+    # exit if q or Q is entered
     if [[ "$game_choice" =~ [qQ] ]]; then
       break
     fi
     local game_chosen="${game_internal_id_arr[$game_choice]}"
+    # restart the menu if input invalid or refresh chosen
     if [[ ! "$game_choice" =~ ^[0-9]+$ ]] || [[ "$game_choice" =~ [Rr] ]] || [[ -z "$game_chosen" ]] ; then
       unset game_title_arr
       continue
@@ -322,8 +339,11 @@ main() {
     local id_chosen="${game_title_arr[$game_chosen]}"
     # echo "$id_chosen: $game_chosen"
     get_download_links "$id_chosen"
+    # reset the menu to load the actual download links
     echo -ne "$reset_menu_area"
+    # master index for the list
     local menu_index=0
+    # giant array with all the links
     local master_links=()
     echo "base game downloads:"
     for (( i=0; i < ${#downlinks[@]}; i++ )); do
@@ -331,7 +351,7 @@ main() {
       master_links[$menu_index]="${downlinks[$i]}"
       (( menu_index++ ))
     done
-    echo "total size of base game installers: $base_size"
+    echo "total size of base game installers: $human_base_size"
     if [[ ${#patches[@]} -gt 0 ]]; then
       echo "patches:"
       for (( i=0; i < ${#patches[@]}; i++ )); do
@@ -355,10 +375,57 @@ main() {
     fi
     echo " use *b - all base installers, *p - all patches, *d - all dlcs, * - every install"
     echo "or you can group it in the format 1,3-5,7-10 to download items 1,3,4,5,7,8,9,10"
-    local mod_selection
-    read -r mod_selection
-    local clean_selection="${mod_selection// /}"
-    local validation_regex="^(\*|\*b|\*p|\*d|[0-9]+|[0-9]+-[0-9]+)$"
+    local is_valid=1
+    while [[ $is_valid -gt 0 ]]; do
+      local all_selected=()
+      local mod_selection
+      read -rp "enter mod selection: " mod_selection
+      local clean_selection="${mod_selection// /}"
+      local validation_regex="^(\*|\*b|\*p|\*d|[0-9]+|[0-9]+-[0-9]+)$"
+      local selection_arr
+      IFS=',' read -ra selection_arr <<< "$clean_selection"
+      for item in "${selection_arr[@]}"; do
+        if [[ ! "$item" =~ $validation_regex ]]; then
+          echo "invalid item: $item, use proper syntax"
+          sleep 2
+          printf '\e[1A\r\e[2K'
+          is_valid=1
+          break
+        fi
+        is_valid=0
+        if [[ $item == "*" ]]; then
+          readarray -d '' -t all_selected < <(printf '%s\0' "${master_links[@]}")
+          break
+        fi
+        if [[ "$item" =~ "*"* ]]; then
+          case "$item" in
+            "*b")
+              readarray -d '' -t all_selected -O ${#all_selected[@]} < <(printf '%s\0' "${downlinks[@]}")
+              ;;
+            "*p")
+              readarray -d '' -t all_selected -O ${#all_selected[@]} < <(printf '%s\0' "${patches[@]}")
+              ;;
+            "*d")
+              readarray -d '' -t all_selected -O ${#all_selected[@]} < <(printf '%s\0' "${dlcs[@]}")
+              ;;
+            "*")
+              ;;
+          esac
+          continue
+        fi
+        IFS='-' read -r start end <<< "$item"
+        if [[ -z $end ]]; then
+          all_selected[${#all_selected[@]}]="${master_links[$start]}"
+        else
+          for ((j=$start; j <= $end; j++)); do
+            if (( j < ${#master_links[@]} )); then
+              all_selected[${#all_selected[@]}]="${master_links[$j]}"
+            fi
+          done
+        fi
+      done
+    done
+
     exit 0
   done
   exit 0
